### ISSUE TITLE
Custom grid size

### ISSUE THREAD

**Issue by AlexChesters** [jamesroutley/24a2#10]
First of all I wanted to say thanks for the awesome project 😄 

It was really easy to get up and running and the [tutorial](https://24a2.routley.io/tutorial/) was amazing!

As far as I can tell currently, the grid size is 24x24 and there's no way to configure that; are there any plans to allow the grid size to be configurable?

Happy to have a crack at implementing it, but I thought I'd get the maintainers thoughts before diving in 😄

**Comment by jamesroutley** [comment]
Heya, thanks for you question and offering to help out!

You can actually configure the grid size, using the undocumented config options `_gridWidth` and `_gridHeight`. 

They're defined here: https://github.com/jamesroutley/24a2/blob/master/src/engine.ts#L63-L74, and you can see an example of it being used here: https://github.com/jamesroutley/24a2/blob/master/website/static/js/landing.js#L20-L21

They're currently undocumented (and explicitly hidden from the reference) to simplify 24a2's interface, but I have a feeling that this will be a common question/request, so I'll consider unhiding it and maybe marking it as `advanced` or something

**Comment by AlexChesters** [comment]
Hey @jamesroutley 😄 

Ah fantastic! Thanks for getting back to me - `_gridWidth` and `_gridHeight` look like they'd do the trick perfectly; I think they would be useful if they were documented (and possibly marked as `advanced` or similar like you suggested 😄 )
