### ISSUE TITLE
Consider dropping P5 as a dependency

### ISSUE THREAD

**Issue by jamesroutley** [jamesroutley/24a2#12]
24a2 uses of [P5.js](https://p5js.org/) to draw things. It uses a very small subset of P5 features, so it seems wasteful to require users to load it. Users also shouldn't have to know about P5 at all. Here are some unstructured thoughts

- At a minimum, we should hide that we're using P5 from users. We can do this by including the bits of P5 that we use in `engine.js`
- We can also remove it entirely by calling the Canvas APIs directly. I've only used Canvas a bit, but I don't think this would be too difficult
- It would be nice if we abstracted 24a2's engine logic from the presentational layer. A couple of people have spoken about using 24a2 to program a 24x24 grid of physical LEDs, and it might be nice to set things up for that.

**Comment by Givup** [comment]
I played around with removing P5.js, and got it working using the Canvas API. [Screenshot P5 vs Canvas API](https://imgur.com/a/eX4BnND).

If we want to separate the engine logic from rendering, this could be done by optionally providing some kinda renderer instance via GameConfig, that implements a simple interface for drawing the dots, defaulting to canvas renderer.

If you want, I can make a branch and tidy up my code a bit, so we can discuss further details if you're interested in the implementation.

**Comment by jes** [comment]
I'd definitely suggest sharing the code that removes P5. I actually came here now to do just that myself.

Re. splitting up engine and rendering: personally I'd want the game to be oblivious of the renderer, so sticking it in GameConfig wouldn't quite be ideal.

For example, it would be relatively easy to make a CLI renderer for 24a2 that draws dots in the terminal. Ideally we'd be able to take a game.js file that runs in 24a2 in the browser, and run it with the CLI version without having to edit any part of the game.js.

I'm also toying with the idea of making a hardware console for 24a2 using an [Espruino](https://www.espruino.com/) (microcontroller that can run JavaScript), and again it would be cool if we could just drop in a game.js file and have it work with no changes required.

**Comment by jamesroutley** [comment]
> It would be nice if we abstracted 24a2's engine logic from the presentational layer

The more I think about splitting this out the more I like it. It lets you do cool things like inject a fake renderer for use in tests - You can start a game, run it for a couple of iterations then assert that certain dots have been set to certain colours. Testing at the moment is pretty difficult because internal logic is closely intertwined with displaying stuff

**Comment by Givup** [comment]
Created PR #13 to share my implementation of replacing p5.js. It replaces all calls to p5, and doesn't try to split the engine logic and rendering.

In summary, the changes are:
- Drawing now uses Canvas API
- Mouse and keyboard input use addEventListener
- "Game loop" is implemented using requestAnimationFrame

Problem with these are that these are only for browsers AFAIK, so when a custom Renderer is implemented, these should be put into a CanvasRenderer or similar.

**Comment by graphnode** [comment]
This should also help with the continuous key press problem refered in this card: https://github.com/jamesroutley/24a2/projects/1#card-36909442

**Comment by jamesroutley** [comment]
Implemented in #28
