### ISSUE TITLE
Sharing games made with 24a2

### ISSUE THREAD

**Issue by andrewnc** [jamesroutley/24a2#14]
I just finished my first game in the engine. It was a great experience (aside from Javascript headaches). 

Do you have a supported channel for sharing the games?

**Comment by jamesroutley** [comment]
Hey! Is your game hosted on a webpage somewhere? If so, we can link to it on our [README](https://github.com/jamesroutley/24a2#games-built-with-24a2).

**Comment by Givup** [comment]
I tested uploading a [24a2 project](https://givup.itch.io/24a2-test) on itch.io. The password for the game is "24a2-is-awesome" without the quotes. This seems like a good way to share if somebody doesn't have a personal webpage. The project uses #13, so I can't say for sure it'll work with current master.

**Comment by andrewnc** [comment]
> Hey! Is your game hosted on a webpage somewhere? If so, we can link to it on our [README](https://github.com/jamesroutley/24a2#games-built-with-24a2).

Yes!!
https://andrewnc.github.io/games/pal_game.html

**Comment by jamesroutley** [comment]
Nice - I've linked to it in this commit https://github.com/jamesroutley/24a2/commit/fbd3755c8f95a12dfafec0ccdd5e34569593b1a3. I've linked back to your website, but please feel free to open a PR if you'd like it to link somewhere else

**Comment by jamesroutley** [comment]
> I tested uploading a 24a2 project on itch.io

@Givup yeah itch.io seems like an obvious place - I'll test it out with master and write up some instructions

**Comment by kentbrew** [comment]
I made samegame on 24a2, pretty smooth experience. Play here:

 https://kentbrew.neocities.org/samegame/

Remix from here:

https://github.com/kentbrew/samegame/

Thanks for doing this! I learned a ton!

**Comment by kentbrew** [comment]
Left a pull request to add samegame to readme.md.
