### ISSUE TITLE
Update library file path in https://24a2.routley.io/tutorial/

### ISSUE THREAD

**Issue by awavering** [jamesroutley/24a2#18]
The [jsdelivr endpoint](https://cdn.jsdelivr.net/gh/jamesroutley/24a2@v0.1/build/engine.js) mentioned in the tutorial looks like an older release that doesn't include recent features found in the docs like _defaultDotColor_.

Seems like updating the tutorial link to the [version-agnostic endpoint](https://cdn.jsdelivr.net/gh/jamesroutley/24a2/build/engine.js) could save people some time and headache.

**Comment by jamesroutley** [comment]
Yes this makes a lot of sense.

> could save people some time and headache.

Sorry about this it - must have been frustrating.

I've fixed this in https://github.com/jamesroutley/24a2/commit/de4eb4e98f3710c44fce3e4e127ba0a877b40102
