### ISSUE TITLE
Feature request: custom grid size

### ISSUE THREAD

**Issue by avetisk** [jamesroutley/24a2#19]
While the concept (and the name!) are sticking to a 24x24 grid, which I guess is much part of the KISS, I still feel that allow custom size grids would be great. 

From the features, there’s evidence that the power of the library is not based as much on the small grid size as it is on the simple API.

**Comment by jamesroutley** [comment]
👍 I've just implemented this in v0.2 - you can set the height and width with `GameConfig.gridHeight` and `GameConfig.gridWidth` https://24a2.routley.io/reference/interfaces/gameconfig/#optional-gridheight
