### ISSUE TITLE
Helter Shelter - a game based on the 24a2 engine

### ISSUE THREAD

**Issue by tolbish** [jamesroutley/24a2#27]
Hello there! I made a game called Helter Shelter based on the 24a2 engine and had a blast doing it. l am familiar with JavaScript but it isn't my main language, so it's nice being able to just focus on making something fun. 

It can be played at https://tolbish.github.io/helter-shelter

**Comment by jamesroutley** [comment]
Thanks! Added in https://github.com/jamesroutley/24a2/commit/1e0892ab7c6e9691a2876f878b1fbead1bb877be
