### ISSUE TITLE
Configurable clear color

### ISSUE THREAD

**Issue by Givup** [jamesroutley/24a2#6]
Instead of always clearing with *Color.Gray*, maybe add a *clearColor* field to config that defaults to *Color.Gray*. This way user doesn't have to overwrite the colors manually.
```javascript
var config = {
  clearColor: Color.Black // Change clear color to black
}
```

**Comment by jamesroutley** [comment]
@Givup Thanks for taking the time for opening this issue! 

This makes sense to me - I think my only hesitation is around the naming. `clearColor` makes sense in the context of the engine (it's the colour we use after calling `clear()`), but I don't think it's obvious in the context of using the engine. 

I think something like `defaultDotColor` might make sense? I also considered `gridColor` and `backgroundColor` which are shorter, but I think less descriptive. `backgroundColor` in particular has a meaning in CSS which we don't want to invoke

**Comment by Givup** [comment]
@jamesroutley 

```defaultDotColor``` is descriptive and makes sense.

```gridColor``` and ```backgroundColor``` could be thought as the background of the grid, not the dots itself. Maybe ```backgroundColor``` could be used for that purpose if wanted later.
