### ISSUE TITLE
A list of featured games?

### ISSUE THREAD

**Issue by jes** [jamesroutley/24a2#7]
You could add a list of games that people have made to the website or README.md or both so that they're more easily discoverable.

I'm currently working on a Space Invaders clone, playable at https://incoherency.co.uk/24invaders/ mostly works already, but I have a bit more graphics work to do.

And, for what it's worth, I *love* 24a2. It brings back the fun that got me into programming in the first place.

**Comment by jamesroutley** [comment]
Yep this is a great idea - I've added a list in [this commit](https://github.com/jamesroutley/24a2/commit/30a38cd78fe8161cf4c0e9ce28aaf8dd51cbd195), and added a link to your game. I've linked back to your website - please let me know if you'd like me to link somewhere else, or feel free to open a pull request. 

Your game is so cool by the way! I love the level and game over screens

**Comment by jes** [comment]
Thanks!
